name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [ main ]  # change if your default branch is different

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docusaurus-site   # npm commands run here
    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install dependencies
      - run: npm ci

      # 4. Build the Docusaurus site
      - run: npm run build

      # 5. Debug: list the build folder to confirm it exists
      - name: List build folder
        run: ls -R ./build

      # 6. Upload the build folder artifact for GitHub Pages
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build   # correct path relative to working-directory

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v1
