name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docusaurus-site  # <- this ensures npm sees package-lock.json
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci                       # runs in docusaurus-site
      - run: npm run build                 # build the site
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./build                    # build folder relative to docusaurus-site
  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v1
